stages:
  - build
  - test

variables:
  COMPOSER_ALLOW_SUPERUSER: 1


.build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

unit-test:
  stage: test
  image: registry.socs.uoguelph.ca/cis3760_f23/f23_cis3760_303:latest
  script:
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit
