# Define stages
stages:
  - example-test

# Set pipeline to only trigger when merging to main branch
#workflow:
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

# Example job
test:
  stage: example-test
  image: cylab/php74
  before_script:
    # use our custom .env file

    # install the application
    - COMPOSER_CACHE_DIR=composer-cache composer install
    - php artisan key:generate
    - php artisan migrate

  # run the tests
  script:
    - vendor/bin/phpunit

  # what we want to store locally to speed up the next run of this job
  cache:
    paths:
      - composer-cache/
      - node_modules/
