stages:
  - build
  - test

variables:
  COMPOSER_ALLOW_SUPERUSER: 1


.build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/laravel-app"
      --dockerfile "${CI_PROJECT_DIR}/laravel-app/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/laravel:1.0"

unit-test:
  stage: test
  image: registry.socs.uoguelph.ca/cis3760_f23/f23_cis3760_303/laravel:1.0
  script:
    - cd laravel-app
    - composer install
    - cp .env.example .env
    - php artisan key:generate
#    - php artisan migrate
    - vendor/bin/phpunit
  cache:
    paths:
      - laravel-app/vendor
