openapi: 3.0.3
info:
  title: Course API
  description: |-
    This is a Course API based on the OpenAPI V3 specification.
  version: "1.0"
servers:
  - url: https://cis3760f23-11.socs.uoguelph.ca/api/v1
tags:
  - name: course
    description: CRUD methods for course data
paths:
  /course/{courseCode}:
    get:
      tags:
        - course
      summary: Find course by course code
      description: Returns a single course
      operationId: getCourseByCode
      parameters:
        - name: courseCode
          in: path
          description: Course code of course to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'          
        '400':
          description: Invalid course code supplied
        '404':
          description: Course not found
    delete:
      tags:
        - course
      summary: Deletes a course
      description: delete a course
      operationId: deleteCourse
      parameters:
        - name: courseCode
          in: path
          description: Course code to delete
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid course code
  /course:
    post:
      tags:
        - course
      summary: Add a new course
      description: Add a new course to the database
      operationId: createCourse
      requestBody:
        description: Create a new course in the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'          
        '405':
          description: Invalid input
    put:
      tags:
        - course
      summary: Update an existing course
      description: Update an existing course by course code
      operationId: updateCourse
      requestBody:
        description: Update an existent course in the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Course'
        '400':
          description: Invalid course code supplied
        '404':
          description: Course not found
components:
  schemas:
    Course:
      type: object
      properties:
        courseCode:
          type: string
          example: 'CIS2750'
        courseName:
          type: string
          example: 'Software Systems Development and Integration'
        courseWeight:
          type: number
          example: 0.75
        courseDescription:
          type: string
          example: 'Example desc'
        courseOffering:
          type: string
          example: 'Winter'
        prereqCourses:
          type: string
          example: 'CIS2430, CIS2520'
        prereqCredits:
          type: number
          example: 5.0
        coreqCourses:
          type: string
          example: 'CIS3750'
        restrictions:
          type: string
          example: 'STAT2070'
        equates:
          type: string
          example: 'CIS3760'
        department:
          type: string
          example: 'School of Computer Science'
        location:
          type: string
          example: 'TBD'
      required:
        - courseCode
        - courseName
        - courseWeight
        - courseDescription
        - courseOffering
