openapi: 3.0.3
info:
  title: Course API
  description: |-
    This is a Course API based on the OpenAPI V3 specification.
  version: "1.0"
servers:
  - url: https://cis3760f23-11.socs.uoguelph.ca/api
tags:
  - name: course
    description: CRUD methods for course data
paths:
  /course/{courseCode}:
    get:
      tags:
        - course
      summary: Find course by course code
      description: Returns a single course
      operationId: getCourseByCode
      parameters:
        - name: courseCode
          in: path
          description: Course code of course to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'          
        '400':
          description: Invalid course code supplied
        '404':
          description: Course not found
    delete:
      tags:
        - course
      summary: Deletes a course
      description: delete a course
      operationId: deleteCourse
      parameters:
        - name: courseCode
          in: path
          description: Course code to delete
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid course code
  /course:
    post:
      tags:
        - course
      summary: Add a new course
      description: Add a new course to the database
      operationId: createCourse
      requestBody:
        description: Create a new course in the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'          
        '405':
          description: Invalid input
    put:
      tags:
        - course
      summary: Update an existing course
      description: Update an existing pet by course code
      operationId: updateCourse
      requestBody:
        description: Update an existent course in the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Course'
        '400':
          description: Invalid course code supplied
        '404':
          description: Course not found
components:
  schemas:
    Course: # TO BE UPDATED
      type: object
      properties:
        courseCode:
          type: string
          example: 'CIS2500'
  
